name: Update README

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.README_GITHUB_TOKEN }}  # Use PAT for git operations
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt
    
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.README_GITHUB_TOKEN }}
      run: python src/build_readme.py
    
    - name: Configure git
      run: |
        git config --global user.name "README Bot"
        git config --global user.email "action@github.com"
    
    - name: Commit and push changes
      run: |
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update README with latest content"
          git push
        fi
